name: "drcjudge"
description: "Assess DRC JSON result file"
runs:
  using: docker
  image: "docker://docker.io/faryon93/drcjudge:latest"
  args:
    - ${{ inputs.result_file }}

inputs:
  result_file:
    description: 'Path to the DRC result file in JSON format'
    required: true
